### ISSUE TITLE
is there a way that we can get no_decimal, thousands_sep

### ISSUE THREAD

**Issue by rudysetiawan** [salarmehr/cosmopolitan#5]
Hi there, is there a way we can get the no_decimal, decimal point, the thousands_sep values? Thank you

**Comment by salarmehr** [comment]
@rudysetiawan Can you provide an example to clarify what are you looking for?

**Comment by salarmehr** [comment]
@rudysetiawan `symbol` function is added. 
Please give it a try. It's in the master branch and will be released 
you can use the symbol name or the constant value.

```
echo (new Cosmo('en'))->symbol('permill');
echo (new Cosmo('en'))->symbol(NumberFormatter::DIGIT_SYMBOL);
```

Supported symbols

- decimal_separator
- grouping_separator
- pattern_separator
- percent
- zero_digit
- digit
- minus_sign
- plus_sign
- currency
- intl_currency
- monetary_separator
- exponential
- permill
- pad_escape
- infinity
- nan
- significant_digit
- monetary_grouping_separator
