### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by franz-josef-kaiser** [salarmehr/cosmopolitan#7]
@salarmehr  Wrapping all the mostly undocumented `intl` stuff isn't easy. So I thought I stop by and leave a _thank you_.

**Comment by salarmehr** [comment]
@franz-josef-kaiser v3 has just been released. You can now use the same interface across multiple languages. Please give it a try, and let me know your thoughts. https://cosmo.miloun.com/?lang=php
