### ISSUE TITLE
overloading function signature must be the same

### ISSUE THREAD

**Issue by frkinta** [salarmehr/cosmopolitan#9]
Just noticed a recurring message in my log

`
PHP Deprecated:  Return type of Salarmehr\Cosmopolitan\Bundle::get($index, $fallback = null) should either be compatible with ResourceBundle::get($index, bool $fallback = true): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/aperassociation/vendor/salarmehr/cosmopolitan/src/Bundle.php on line 20`

PHP 8.1.17 (cli) (built: Mar 16 2023 14:38:37) (NTS)

**Comment by salarmehr** [comment]
@frkinta thanks for bringing this to my attention. I will check it out when I find some free time. Feel free to create a PR.

**Comment by salarmehr** [comment]
@frkinta you can update and verify the fix.
